services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpass
    ports: ["5432:5432"]

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000"]
