services:
  postgres:
    image: postgres:15
    container_name: repsy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repsydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - repsy-net

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    networks:
      - repsy-net

  repsy-api:
    image: repo.repsy.io/huzuntu/repsy-project-docker/repsy-api:1.0.0
    container_name: repsy-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://repsy-postgres:5432/repsydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      STORAGE_STRATEGY: file-system
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - minio
    networks:
      - repsy-net

networks:
  repsy-net:

volumes:
  minio-data:
  postgres-data: